//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Pharmacy__Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackProduct
    {
        public int ID { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Content { get; set; }
        public int SendBy { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> ReplyID { get; set; }
        public Nullable<int> ReplyBy { get; set; }
        public bool Status { get; set; }
    }
}
