//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Pharmacy__Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackRecruiment
    {
        public int ID { get; set; }
        public int ReplyBy { get; set; }
        public int LetterID { get; set; }
        public string Content { get; set; }
    
        public virtual CoverLetters CoverLetters { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
