//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Pharmacy__Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidFillings
    {
        public int ProductID { get; set; }
        public Nullable<double> AirPressure { get; set; }
        public Nullable<double> AirVolume { get; set; }
        public Nullable<int> FillingSpeed { get; set; }
        public Nullable<int> FillingRange { get; set; }
    }
}
