//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Pharmacy__Server.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlinePharmacyEntities : DbContext
    {
        public OnlinePharmacyEntities()
            : base("name=OnlinePharmacyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CoverLetters> CoverLetters { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<EducationDetails> EducationDetails { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Encapsulations> Encapsulations { get; set; }
        public virtual DbSet<FeedbackProduct> FeedbackProduct { get; set; }
        public virtual DbSet<FeedbackRecruiment> FeedbackRecruiment { get; set; }
        public virtual DbSet<Functions> Functions { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<LiquidFillings> LiquidFillings { get; set; }
        public virtual DbSet<Organizations> Organizations { get; set; }
        public virtual DbSet<PersonalDetails> PersonalDetails { get; set; }
        public virtual DbSet<ProductImages> ProductImages { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductTypes> ProductTypes { get; set; }
        public virtual DbSet<RecruimentNews> RecruimentNews { get; set; }
        public virtual DbSet<Resume> Resume { get; set; }
        public virtual DbSet<Tablets> Tablets { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
