//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Pharmacy__Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume
    {
        public int LetterID { get; set; }
        public Nullable<double> YearOfExp { get; set; }
        public string OldOrg { get; set; }
        public string Website { get; set; }
        public string Note { get; set; }
    }
}
